# Generated by Django 3.0.6 on 2020-08-22 09:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSignsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(null=True)),
                ('bool_pressure', models.IntegerField(null=True)),
                ('heartbeat', models.IntegerField(null=True)),
                ('breathing', models.IntegerField(null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 8, 22, 16, 40, 26, 157109), null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vital_signs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
