# Generated by Django 3.0.6 on 2020-08-22 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vital_signs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsignsmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 15, 48, 9, 680436, tzinfo=utc), null=True),
        ),
    ]
