# Generated by Django 3.0.6 on 2020-08-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vital_signs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitalsignsmodel',
            old_name='hearbeat',
            new_name='heartbeat',
        ),
    ]
