# Generated by Django 3.0.6 on 2020-08-13 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vital_signs', '0002_auto_20200813_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsignsmodel',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
