# Generated by Django 3.0.6 on 2020-08-29 05:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vital_signs', '0003_auto_20200828_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsignsmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 5, 18, 9, 854306, tzinfo=utc), null=True),
        ),
    ]
