# Generated by Django 3.0.6 on 2020-08-13 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vital_signs', '0004_auto_20200813_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsignsmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 15, 58, 5, 22459, tzinfo=utc)),
        ),
    ]
