# Generated by Django 3.0.6 on 2020-08-14 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_signs', '0006_auto_20200813_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsignsmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 22, 2, 10, 666957)),
        ),
    ]
