# Generated by Django 3.0.6 on 2020-08-15 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_signs', '0007_auto_20200814_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsignsmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 15, 20, 23, 51, 84721), null=True),
        ),
    ]
