# Generated by Django 3.0.6 on 2020-08-18 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_signs', '0010_auto_20200816_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsignsmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 20, 58, 45, 900733), null=True),
        ),
    ]
