# Generated by Django 3.0.6 on 2020-08-18 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_signs', '0011_auto_20200818_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsignsmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 21, 19, 56, 472790), null=True),
        ),
    ]
