# Generated by Django 3.0.6 on 2020-08-22 09:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalRecordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=300)),
                ('disease', models.CharField(max_length=300, null=True)),
                ('start_time', models.DateField(default=datetime.date.today, null=True)),
                ('status', models.CharField(choices=[('In process', 'In process'), ('Done', 'Done')], max_length=11, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hospital_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
