# Generated by Django 3.0.6 on 2020-08-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalrecordmodel',
            options={'ordering': ['-start_time']},
        ),
    ]
