# Generated by Django 3.0.6 on 2020-08-18 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalrecordmodel',
            name='disease',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hospitalrecordmodel',
            name='start_time',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='hospitalrecordmodel',
            name='status',
            field=models.CharField(choices=[('Y', 'In process'), ('N', 'Done')], max_length=1, null=True),
        ),
    ]
