# Generated by Django 3.0.6 on 2020-08-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_record', '0002_auto_20200818_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalrecordmodel',
            name='status',
            field=models.CharField(choices=[('In process', 'In process'), ('Done', 'Done')], max_length=11, null=True),
        ),
    ]
