# Generated by Django 3.0.6 on 2020-08-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_record', '0002_auto_20200830_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalrecordmodel',
            options={'ordering': ['-disease']},
        ),
    ]
