# Generated by Django 3.0.6 on 2020-08-09 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('physical', '0002_auto_20200808_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='physicalmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_physical', to=settings.AUTH_USER_MODEL),
        ),
    ]
