# Generated by Django 3.0.6 on 2020-08-12 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0003_auto_20200809_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalmodel',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
