# Generated by Django 3.0.6 on 2020-08-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0004_auto_20200812_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicalmodel',
            options={'ordering': ['-date']},
        ),
    ]
