# Generated by Django 3.0.6 on 2020-08-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_examination', '0001_initial'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaldetailmodel',
            options={'ordering': ['-medical']},
        ),
        migrations.AddField(
            model_name='medicaldetailmodel',
            name='dates',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='medicaldetailmodel',
            unique_together={('re_examination', 'medical')},
        ),
    ]
