# Generated by Django 3.0.6 on 2020-08-30 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_vn', models.IntegerField(null=True)),
                ('death_vn', models.IntegerField(null=True)),
                ('recoverd_vn', models.IntegerField(null=True)),
                ('case_w', models.IntegerField(null=True)),
                ('death_w', models.IntegerField(null=True)),
                ('recoverd_w', models.IntegerField(null=True)),
                ('date', models.DateField(null=True, verbose_name=datetime.date.today)),
            ],
        ),
    ]
